[tool.poetry]
name = "bb"
version = "0.1.0"
description = ""
authors = ["apehex <apehex@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
crypto = '*'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
